### ISSUE TITLE
where is sdchain.sln

### ISSUE THREAD

**Issue by diliuhua** [SDChain/SDChain-Core#1]
Hello， I can not find sdchain.sln in this project.
Can you tell me where is "Builds/Visual Studio 2015/sdchain.sln" which descriped in 《VisualStudio2015上编译安装SDChain-Core流程.md》
Thank you！

**Comment by BeBeMo** [comment]
Now it shows a part of the code.In a few months,we will release the complete source code,you can compile it by then.
We suggest that you can go to https://forum.sdchain.io/ to get more information about community participation.
