### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by songky** [SDChain/SDChain-Core#3]
How could I connect to the testnet ? Can I apply some test coins ?

**Comment by aalpou** [comment]
You can visit the site(https://github.com/SDChain/wiki/tree/master/SDA-Wallet-Design-Contest)，and the document named 'Participate-SDChain-Community-EN.pdf' will tell you the specific steps.

**Comment by songky** [comment]
Thanks

**Comment by aalpou** [comment]
My pleasure.
