### ISSUE TITLE
please remove packaged binary from git (*.tar.gz)

### ISSUE THREAD

**Issue by JokerCatz** [SDChain/SDChain-Core#4]
first , if i clone this git use like this

    git clone https://github.com/SDChain/SDChain-Core.git

will cost me "664MB" disk size and very very long time to sync ... I think it very close ubuntu image size ... are you make a OS or node?

please remove the stupid packaged binary from git , you can add a builder like dockerfile / docker-compose to support auto-complete / deploy , or just use github "Releases" to than me download the release binary like Bitcoin / Parity / Bitcoin-Unlimited ...

https://help.github.com/articles/creating-releases/

====================

首先，如果我下载这个专案，使用这样的指令

    git clone https://github.com/SDChain/SDChain-Core.git

将会花费我 "664MB" 的硬盘空间，并花费非常久的时间在做下载 ... 我想这个档案大小非常接近於 Ubuntu 映像档 ... 请问你们在做系统还是同步节点？

请从 git 上移除那个愚蠢的编译好的档案，你可以增加类似 dockerfile / docker-compose 來实现自动编译和部署，或是单纯的使用 github 所提供的 "Releases" 功能，让我下载编译好的东西即可，像是 Bitcoin / Parity / Bitcoin-Unlimited ...

https://help.github.com/articles/creating-releases/

====================

首先，如果我下載/同步這個專案，使用這樣的指令

    git clone https://github.com/SDChain/SDChain-Core.git

將會花費我 "664MB" 的硬碟空間，並花費非常久的時間在做同步 ... 我想這個檔案大小非常接近於 Ubuntu 映像檔 ... 請問你們在做系統還是同步節點？

請從 git 上移除那個愚蠢的編譯好的檔案，你可以增加類似 dockerfile / docker-compose 來實現自動編譯和部署，或是單純的使用 github 所提供的 "Releases" 功能，讓我下載編譯好的東西即可，像是 Bitcoin / Parity / Bitcoin-Unlimited ...

https://help.github.com/articles/creating-releases/

**Comment by SDChain** [comment]
https://github.com/SDChain/SDChain-Core/releases/tag/0.4.1-c

**Comment by JokerCatz** [comment]
...... 別只弄這個，我剛剛說的包含你們必須清理這個 git repo 才行，類似使用 rebase 強制剔除該檔案，否則下個受害者還是一樣的 664MB，尤其你們 doc 內寫的必須使用的 `SDChain-core.cfg` / `validators.txt` / `libprotobuf.so.8` 這幾個檔案 ...

https://docs.microsoft.com/en-us/azure/devops/articles/remove-binaries?view=vsts

我知道這是個硬仗，不過 ... 請你們好好的清除它，並且以後也不要再這樣使用 git ... 如果你感覺麻煩，我想其他人會感覺更麻煩 ...

----------------

...... 别只弄这个，我刚刚说的包含你们必须清理这个 git repo 才行，类似使用 rebase 强制剔除该档案，否则下个受害者还是一样的 664MB，尤其你们 doc 内写的必须使用的 `SDChain-core.cfg` / `validators.txt` / `libprotobuf.so.8` 这几个档案 ...

https://docs.microsoft.com/en-us/azure/devops/articles/remove-binaries?view=vsts

我知道这是个硬仗，不过 ... 请你们好好的清除它，并且以後也不要再这样使用 git ... 如果你感觉麻烦，我想其他人会感觉更麻烦 ...

**Comment by brlin-tw** [comment]
You need something like [BFG Repo-Cleaner by rtyley](https://rtyley.github.io/bfg-repo-cleaner/) to clean up the history and do a force-push to rewrite the repo on GitHub.
